spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/std_db
    username: admin
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: create-drop
    show-sql: true