spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 1

    job-store-type: memory

  profiles:
    active: dev

  hateoas:
    use-hal-as-default-json-media-type: false