spring:
  jpa:
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.order_inserts: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  profiles:
    active: prod

  hateoas:
    use-hal-as-default-json-media-type: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/realms/security}


server:
  port: ${PORT}