spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/std_db
    username: admin
    password: pass
    driver-class-name: org.postgresql.Driver

  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 1

    job-store-type: memory

  profiles:
    active: dev